name: 'Setup Go Cache'
description: 'Sets up caching for Go modules and build cache'

outputs:
  cache-hit:
    description: 'Whether there was a cache hit'
    value: ${{ steps.cache-go-with-tools.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: cache-go-with-tools
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/.cache/golangci-lint
        key: v1-go-${{ runner.os }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          v1-go-${{ runner.os }}- 