name: release-plz-pr

permissions:
  contents: write # To create/update a release-plz branch.
  pull-requests: write # To create/update a PR from release-plz branch.

on:
  push:
    branches:
      - 'master' # Must be the same as ${{ vars.RELEASE_PLZ_TARGET_BRANCH || 'master' }.

concurrency:
  group: release-plz

jobs:
  release-plz-pr:
    # Do not run in repo forks and release-plz commits.
    if: >-
      ${{
        github.repository_owner == 'powerman' &&
        ! contains(github.event.head_commit.message, (vars.RELEASE_PLZ_COMMIT_PREFIX || 'chore: release')) &&
        ! (contains(github.event.head_commit.message, 'Merge pull request') &&
           contains(github.event.head_commit.message, format('from {0}', (vars.RELEASE_PLZ_PR_BRANCH || 'release-plz'))))
      }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable `git push` when `act` is run without `--no-skip-checkout`
        if: ${{ env.ACT }}
        run: git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - uses: ./.github/actions/release-plz-pr
        with:
          target_branch: ${{ vars.RELEASE_PLZ_TARGET_BRANCH }}
          pr_branch: ${{ vars.RELEASE_PLZ_PR_BRANCH }}
          commit_prefix: ${{ vars.RELEASE_PLZ_COMMIT_PREFIX }}
