name: release-plz-pr-update

permissions:
  contents: write # To update release-plz branch.
  pull-requests: write # To update PR title and body.

on:
  pull_request:
    types: [edited]
    branches:
      - 'master' # Must be the same as ${{ vars.RELEASE_PLZ_TARGET_BRANCH || 'master' }.

concurrency:
  group: release-plz

jobs:
  update-release-branch:
    if: >-
      ${{
        github.repository_owner == 'powerman' &&
        github.head_ref == (vars.RELEASE_PLZ_PR_BRANCH || 'release-plz') &&
        github.event.changes.title
      }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable `git push` when `act` is run without `--no-skip-checkout`
        if: ${{ env.ACT }}
        run: git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - uses: ./.github/actions/release-plz-pr-update
        with:
          target_branch: ${{ vars.RELEASE_PLZ_TARGET_BRANCH }}
          pr_branch: ${{ vars.RELEASE_PLZ_PR_BRANCH }}
          commit_prefix: ${{ vars.RELEASE_PLZ_COMMIT_PREFIX }}
